"""empty message

Revision ID: 93c23b67f97a
Revises: 587c76a69abe
Create Date: 2023-02-19 14:21:06.046032

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '93c23b67f97a'
down_revision = '587c76a69abe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_profile_id'), 'profile', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_id'), table_name='profile')
    op.drop_table('profile')
    # ### end Alembic commands ###
